"""Install session autostart files for the current Python environment."""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

NAME = "linux-dot-panel"
MARKER = "Generated by linux-dot-panel"


def _config_home() -> Path:
    return Path(os.environ.get("XDG_CONFIG_HOME") or Path.home() / ".config")


def _desktop_path() -> Path:
    return _config_home() / "autostart" / f"{NAME}.desktop"


def _service_path() -> Path:
    return _config_home() / "systemd" / "user" / f"{NAME}.service"


def _desktop_argument(value: str) -> str:
    """Quote an Exec argument using desktop entry escaping rules."""
    escaped = value.replace("\\", "\\\\\\\\")
    for character in ('"', "`", "$"):
        escaped = escaped.replace(character, "\\\\" + character)
    return '"' + escaped.replace("%", "%%") + '"'


def _systemd_argument(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("%", "%%")
    return f'"{escaped}"'


def _desktop_file(python: Path) -> str:
    command = f"{_desktop_argument(str(python))} -m linux_dot_panel daemon"
    return (
        "[Desktop Entry]\n"
        "Type=Application\n"
        "Name=Linux Dot Panel\n"
        "Comment=Emoji and clipboard panel\n"
        f"Exec={command}\n"
        f"TryExec={python}\n"
        "Terminal=false\n"
        "X-GNOME-Autostart-enabled=true\n"
        f"X-Linux-Dot-Panel-Managed={MARKER}\n"
    )


def _service_file(python: Path) -> str:
    return (
        f"# {MARKER}\n"
        "[Unit]\n"
        "Description=Linux Dot Panel\n"
        "PartOf=graphical-session.target\n"
        "After=graphical-session.target\n"
        "\n"
        "[Service]\n"
        "Type=simple\n"
        f"ExecStart={_systemd_argument(str(python))} -m linux_dot_panel daemon\n"
        "Restart=on-failure\n"
        "RestartSec=2\n"
        "\n"
        "[Install]\n"
        "WantedBy=graphical-session.target\n"
    )


def _managed(path: Path) -> bool:
    return path.exists() and MARKER in path.read_text(encoding="utf-8")


def _write_managed(path: Path, content: str) -> None:
    if path.exists() and not _managed(path):
        raise FileExistsError(f"Refusing to replace an existing file: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def install(method: str = "xdg") -> Path:
    """Enable a single session startup method, beginning at the next login."""
    if method not in ("xdg", "systemd"):
        raise ValueError(f"Unknown autostart method: {method}")
    other = _service_path() if method == "xdg" else _desktop_path()
    if other.exists():
        raise FileExistsError(f"Remove the other autostart method first: {other}")
    python = Path(sys.executable).resolve()
    if method == "xdg":
        path = _desktop_path()
        _write_managed(path, _desktop_file(python))
    else:
        path = _service_path()
        _write_managed(path, _service_file(python))
        try:
            subprocess.run(["systemctl", "--user", "daemon-reload"], check=True)
            subprocess.run(["systemctl", "--user", "enable", path.name], check=True)
        except (OSError, subprocess.CalledProcessError):
            path.unlink()
            raise
    return path


def uninstall() -> list[Path]:
    """Remove only autostart files created by this application."""
    removed = []
    service = _service_path()
    if _managed(service):
        subprocess.run(["systemctl", "--user", "disable", "--now", service.name], check=True)
        service.unlink()
        subprocess.run(["systemctl", "--user", "daemon-reload"], check=True)
        removed.append(service)
    desktop = _desktop_path()
    if _managed(desktop):
        desktop.unlink()
        removed.append(desktop)
    return removed
